### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by uvulpos** [z3dm4n/k8s-dev-cluster-hcloud#6]
just asking, if the repo is getting updates if needed, or if the project is abonded?

**Comment by z3dm4n** [comment]
Hi Tim,

2 years ago I created this GitHub repo as part of a POC. Since then, I haven't actively worked on it myself as it had served its purpose for me. However, if there is interest in me updating this POC code, I would be happy to do so. But please do not expect ongoing updates...

But if someone wants to participate, then go ahead.

Best regards
Erik

**Comment by uvulpos** [comment]
Hi Erik,
thanks for answering. I would be interested in contributing to the project if I can fix any issues. But it would be nice if I wouldn't be the only maintainer. :)

**Comment by z3dm4n** [comment]
Feel free to fork this repo and I'll be contributor. This makes more sense for me personally.
